# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  agent_output.schema.json
#   timestamp: 2026-05-07T15:58:14+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AgentId(StrEnum):
    MI = "MI"
    CSK = "CSK"
    RCB = "RCB"
    DC = "DC"
    KKR = "KKR"
    RR = "RR"
    PBKS = "PBKS"
    SRH = "SRH"
    LSG = "LSG"
    GT = "GT"


class Action(StrEnum):
    pass_ = "pass"
    bid = "bid"
    raise_ = "raise"
    drop = "drop"


class ScoreBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    form_score: float
    role_fit: float
    home_ground_fit: float
    career_score: float
    phase_fit: float
    injury_risk: float
    social_buzz: float
    price_elasticity: float
    total: float


class Rationale(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    score_breakdown: ScoreBreakdown
    reasoning_summary: Annotated[
        str, Field(description="Human-readable summary (≤80 words).", max_length=500)
    ]
    is_cold_start: Annotated[
        bool | None,
        Field(
            description="True when data_coverage_score < 0.5 for this player (§16.1)."
        ),
    ] = None


class ChosenPlan(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


class AgentOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_id: Annotated[AgentId, Field(description="Franchise identifier.")]
    timestamp: Annotated[
        AwareDatetime,
        Field(
            description="ISO-8601 UTC timestamp of when the agent produced this output."
        ),
    ]
    player_id: Annotated[
        str, Field(description="Canonical player identifier from the feature store.")
    ]
    action: Annotated[
        Action,
        Field(description="Action the agent has chosen for this nomination cycle."),
    ]
    bid_amount: Annotated[
        float | None,
        Field(
            description="Bid amount in INR. Must be null when action is 'pass' or 'drop'.",
            ge=0.0,
        ),
    ] = None
    confidence_score: Annotated[
        float,
        Field(
            description="Confidence in the chosen action. Used to rank active bidders.",
            ge=0.0,
            le=1.0,
        ),
    ]
    rationale: Rationale
    chosen_plan: Annotated[
        ChosenPlan, Field(description="Which agent plan this action maps to.")
    ]
