# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  auction_state.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Phase(StrEnum):
    prep = "prep"
    nominating = "nominating"
    opening_bid = "opening_bid"
    open_bidding = "open_bidding"
    closing = "closing"
    sold = "sold"
    unsold = "unsold"
    ended = "ended"


class CurrentPlayer(BaseModel):
    player_id: str
    base_price: Annotated[float, Field(ge=0.0)]
    current_bid: Annotated[float, Field(ge=0.0)]
    current_bidder: str | None
    bid_count: Annotated[int, Field(ge=0)]


class SquadItem(BaseModel):
    player_id: str
    price_paid: float
    role: str
    is_overseas: bool


class Teams(BaseModel):
    budget_remaining: Annotated[float, Field(ge=0.0)]
    squad: list[SquadItem]
    overseas_count: Annotated[int, Field(ge=0, le=8)]
    warnings: Annotated[int, Field(ge=0, le=3)]


class AuctionState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auction_id: UUID
    phase: Phase
    current_player: CurrentPlayer | None = None
    active_bidders: Annotated[list[str] | None, Field(max_length=2)] = None
    standby_queue: list[str] | None = None
    teams: Annotated[dict[str, Teams], Field(description="Keyed by agent_id.")]
    nomination_order: list[str]
    sold_players: list[str]
    unsold_players: list[str]
    remaining_pool: list[str]
    last_event_seq: Annotated[int | None, Field(ge=0)] = None
    seed: int | None = None
