# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  auction_event.schema.json
#   timestamp: 2026-05-09T20:07:16+00:00

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Type(StrEnum):
    auction_started = "auction.started"
    auction_paused = "auction.paused"
    auction_resumed = "auction.resumed"
    auction_ended = "auction.ended"
    player_nominated = "player.nominated"
    bid_placed = "bid.placed"
    bid_raised = "bid.raised"
    bid_dropped = "bid.dropped"
    bid_rejected = "bid.rejected"
    player_sold = "player.sold"
    player_unsold = "player.unsold"
    agent_timeout = "agent.timeout"
    agent_cooldown = "agent.cooldown"
    snapshot_taken = "snapshot.taken"


class AgentId(Enum):
    MI = "MI"
    CSK = "CSK"
    RCB = "RCB"
    DC = "DC"
    KKR = "KKR"
    RR = "RR"
    PBKS = "PBKS"
    SRH = "SRH"
    LSG = "LSG"
    GT = "GT"
    NoneType_None = None


class AuctionEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: UUID
    auction_id: UUID
    seq: Annotated[
        int,
        Field(
            description="Monotonically increasing sequence number per auction_id.", ge=1
        ),
    ]
    type: Type
    payload: Annotated[
        dict[str, Any],
        Field(description="Event-type-specific data. Shape depends on 'type'."),
    ]
    timestamp: AwareDatetime
    agent_id: Annotated[
        AgentId | None, Field(description="Present when the event is agent-specific.")
    ] = None
