# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  cold_start_profile.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ImputedMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    strike_rate: Annotated[float, Field(ge=0.0)]
    economy: Annotated[float, Field(ge=0.0)]
    role_fit: Annotated[float, Field(ge=0.0, le=1.0)]


class SourceSignal(StrEnum):
    domestic_scorecards = "domestic_scorecards"
    scout_reports = "scout_reports"
    auction_history = "auction_history"
    declared_role = "declared_role"


class ColdStartProfile1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cohort_ids: Annotated[list[str], Field(min_length=1)]
    cohort_size: Annotated[int, Field(ge=1)]
    imputed_metrics: ImputedMetrics
    source_signals: Annotated[list[SourceSignal], Field(min_length=1)]
    data_coverage_score: Annotated[float, Field(ge=0.0, le=1.0)]
    imputation_confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class ProvenanceItem(BaseModel):
    source: str
    fetched_at: AwareDatetime
    type: str


class ColdStartProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    player_id: str
    cold_start_profile: ColdStartProfile1
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    provenance: Annotated[list[ProvenanceItem], Field(min_length=1)]
