# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  headshot_metadata.schema.json
#   timestamp: 2026-05-09T20:07:26+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field


class AssetSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    webp: AnyUrl
    avif: AnyUrl | None = None
    jpeg: AnyUrl


class Sizes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_64: Annotated[AssetSet, Field(alias="64")]
    field_256: Annotated[AssetSet, Field(alias="256")]
    field_512: Annotated[AssetSet, Field(alias="512")]


class HeadshotMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    player_id: str
    sizes: Sizes
    blurhash: Annotated[str, Field(min_length=6)]
    source: str
    license: str
    fetched_at: AwareDatetime
    is_fallback: bool
