# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  player_feature_v1.schema.json
#   timestamp: 2026-05-09T01:55:28+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Role(StrEnum):
    batter = "batter"
    bowler = "bowler"
    all_rounder = "all-rounder"
    keeper = "keeper"


class RoleSubtype(StrEnum):
    opener = "opener"
    anchor = "anchor"
    finisher = "finisher"
    pp_spinner = "pp-spinner"
    death_bowler = "death-bowler"
    all_rounder = "all-rounder"
    keeper = "keeper"


class SpecialistRatings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    death_bowler: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    powerplay_batter: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    powerplay_bowler: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    anchor: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    finisher: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class StatsBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    matches: Annotated[int | None, Field(ge=0)] = None
    innings: Annotated[int | None, Field(ge=0)] = None
    runs: Annotated[float | None, Field(ge=0.0)] = None
    balls_faced: Annotated[int | None, Field(ge=0)] = None
    average: Annotated[float | None, Field(ge=0.0)] = None
    strike_rate: Annotated[float | None, Field(ge=0.0)] = None
    hundreds: Annotated[int | None, Field(ge=0)] = None
    fifties: Annotated[int | None, Field(ge=0)] = None
    fours: Annotated[int | None, Field(ge=0)] = None
    sixes: Annotated[int | None, Field(ge=0)] = None
    boundary_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    dot_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    wickets: Annotated[int | None, Field(ge=0)] = None
    economy: Annotated[float | None, Field(ge=0.0)] = None
    bowling_avg: Annotated[float | None, Field(ge=0.0)] = None
    bowling_sr: Annotated[float | None, Field(ge=0.0)] = None


class PhaseBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sr: Annotated[float | None, Field(ge=0.0)] = None
    economy: Annotated[float | None, Field(ge=0.0)] = None
    wickets: Annotated[int | None, Field(ge=0)] = None


class PhaseMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    powerplay: PhaseBlock | None = None
    middle: PhaseBlock | None = None
    death: PhaseBlock | None = None


class PlayerFeatureV1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    player_id: str
    canonical_name: str
    role: Role
    role_subtype: RoleSubtype | None = None
    nationality: str
    is_overseas: bool
    data_coverage_score: Annotated[float, Field(ge=0.0, le=1.0)]
    feature_version: Annotated[str, Field(pattern="^feature_v\\d+$")]
    career: StatsBlock
    form_5: StatsBlock | None = None
    form_10: StatsBlock | None = None
    form_20: StatsBlock | None = None
    phase_metrics: PhaseMetrics | None = None
    specialist_ratings: SpecialistRatings | None = None
    venue_splits: Annotated[
        dict[str, StatsBlock] | None, Field(description="Keyed by ground name.")
    ] = None
    base_price_tier: Annotated[
        float | None, Field(description="Base price in INR (e.g., 2000000 = 20L).")
    ] = None
    form_score: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    value_score: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
