# AUTO-GENERATED — do not edit manually.
# Run `make schemas` to regenerate.

# generated by datamodel-codegen:
#   filename:  sag_output.schema.json
#   timestamp: 2026-05-07T15:58:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Last12InningsMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    runs: Annotated[float | None, Field(ge=0.0)] = None
    strike_rate: Annotated[float | None, Field(ge=0.0)] = None
    average: Annotated[float | None, Field(ge=0.0)] = None
    boundary_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    dot_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    wickets: Annotated[float | None, Field(ge=0.0)] = None
    economy: Annotated[float | None, Field(ge=0.0)] = None
    bowling_sr: Annotated[float | None, Field(ge=0.0)] = None


class Powerplay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sr: Annotated[float | None, Field(ge=0.0)] = None
    economy: Annotated[float | None, Field(ge=0.0)] = None


class Middle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sr: Annotated[float | None, Field(ge=0.0)] = None
    economy: Annotated[float | None, Field(ge=0.0)] = None


class Death(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sr: Annotated[float | None, Field(ge=0.0)] = None
    economy: Annotated[float | None, Field(ge=0.0)] = None


class SituationalMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    powerplay: Powerplay | None = None
    middle: Middle | None = None
    death: Death | None = None


class Severity(StrEnum):
    none = "none"
    minor = "minor"
    moderate = "moderate"
    major = "major"


class InjuryStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: str
    timestamp: AwareDatetime
    severity: Severity
    expected_return: AwareDatetime | None = None


class SocialBuzz(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    volume: Annotated[float | None, Field(ge=0.0)] = None
    sentiment: Annotated[float | None, Field(ge=-1.0, le=1.0)] = None
    top_sources: Annotated[list[str] | None, Field(max_length=5)] = None


class ImputedMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    strike_rate: Annotated[float, Field(ge=0.0)]
    economy: Annotated[float, Field(ge=0.0)]
    role_fit: Annotated[float, Field(ge=0.0, le=1.0)]


class ColdStartProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cohort_ids: Annotated[list[str], Field(min_length=1)]
    cohort_size: Annotated[int, Field(ge=1)]
    imputed_metrics: ImputedMetrics
    source_signals: Annotated[list[str], Field(min_length=1)]
    data_coverage_score: Annotated[float, Field(ge=0.0, le=1.0)]
    imputation_confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class Type(StrEnum):
    cricsheet = "cricsheet"
    injury = "injury"
    social = "social"
    api = "api"
    cold_start = "cold_start"
    cache = "cache"


class ProvenanceItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: str
    fetched_at: AwareDatetime
    type: Type
    stale: bool | None = None


class SagOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    player_id: str
    player_summary: Annotated[str, Field(max_length=500)]
    last_12_innings_metrics: Last12InningsMetrics | None = None
    situational_metrics: SituationalMetrics | None = None
    injury_status: InjuryStatus | None = None
    social_buzz: SocialBuzz | None = None
    cold_start_profile: Annotated[
        ColdStartProfile | None,
        Field(
            description="Present when query_type is cold_start or player has data_coverage_score < 0.5."
        ),
    ] = None
    confidence: Annotated[
        float,
        Field(
            description="Overall confidence in this response; degrades with source staleness.",
            ge=0.0,
            le=1.0,
        ),
    ]
    missing_fields: Annotated[
        list[str] | None,
        Field(
            description="Fields that could not be populated due to missing source data."
        ),
    ] = None
    provenance: Annotated[list[ProvenanceItem], Field(min_length=1)]
